version: "3"
services:
    apache2:
        image: webdevops/apache:latest
        
        volumes:
            - ./php/www:/var/www/html
        ports:
            - 80:80
            - 443:443
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
        depends_on: 
            - db
    db:
        image: postgres
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=postgres
            - PGPORT=5432
        volumes:
            - ./database/pg/data:/var/lib/postgresql/data
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_ROOT_PASSWORD: postgres
volumes:
    persistent: